name: Publish NPM
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1

      - name: Publish package
        run: |-
          deno run -A dnt.ts
          cd dnt
          npm publish
